name: Development

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [ assigned, opened, synchronize, reopened, labeled ]

jobs:

  main:
    strategy:
      matrix:
        node-version: [22.x]
    runs-on: ubuntu-latest

    env:
      NPM_TOKEN: ${{secrets.NPM_TOKEN}}

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0

      - name: ⬇️ Checkout
        uses: actions/checkout@v5
        with:
          # https://github.com/lerna/lerna/issues/2542
          # pulls all commits (needed for lerna / semantic release to correctly version)
          fetch-depth: "0"

      - name: ⎔ Use Node Matrix Versions
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org

      - name: ⬇️ Install Dependencies
        run: yarn --frozen-lockfile

      - name: 📋 Format Check
        run: yarn format --check

      - name: ⬣ Eslint
        run: yarn lint

      - name: ⚙️ Build
        run: yarn lerna:build

      - name: 🧪 Run Tests with Coverage
        run: yarn test:coverage:summary
